---
name: Deploy to Github pages and container registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main
jobs:
  deploy:
    name: Deploy MkDocs project to Github pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip3 install -r requirements.txt
      - run: mkdocs gh-deploy --force
